# Generated by Django 3.2.9 on 2021-12-11 16:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211211_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 11, 16, 35, 43, 904611, tzinfo=utc)),
        ),
    ]
